# A Momentum Trading Algorithm 
### Step 1: Choose a basket of stocks to trade from

In [ ]:
import pandas as pd
import requests

url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"

headers = {
    "User-Agent": "Mozilla/5.0"
}

html = requests.get(url, headers=headers).text

tables = pd.read_html(html)

tables[0].head()

C:\Users\Danny\AppData\Local\Temp\ipykernel_4228\4231243312.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html)

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989

In [9]:
tables[1].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 402 entries, 0 to 401
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   (Effective Date, Effective Date)  402 non-null    object
 1   (Added, Ticker)                   383 non-null    object
 2   (Added, Security)                 383 non-null    object
 3   (Removed, Ticker)                 379 non-null    object
 4   (Removed, Security)               379 non-null    object
 5   (Reason, Reason)                  402 non-null    object
dtypes: object(6)
memory usage: 19.0+ KB

In [12]:
tables[1].head()

  Effective Date  Added                      Removed                    \
  Effective Date Ticker             Security  Ticker          Security
0  June 30, 2026    NaN                  NaN     CAG    Conagra Brands
1  June 29, 2026   HONA  Honeywell Aerospace     NaN               NaN
2  June 22, 2026   MRVL   Marvell Technology    POOL  Pool Corporation
3  June 22, 2026   FLEX            Flex Ltd.     CPB        Campbell's
4   June 2, 2026    NaN                  NaN    EPAM      EPAM Systems

                                              Reason
                                              Reason
0                   Market capitalization change.[6]
1  S&P 500 constituent Honeywell spun off Honeywe...
2                   Market capitalization change.[7]
3                   Market capitalization change.[7]
4                   Market capitalization change.[8]

In [ ]:
df = tables[1]
# TODO
df = df[
    []
]